stages:
  - rpm-package
  - local-test
  - rpm-stable

rpm-package:
  stage: rpm-package
  script:
    - 'rpm-package.sh'

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'

rpm-stable:
  stage: rpm-stable
  script:
    - 'rpm-stable.sh'
  only:
    - master
