stages:
  - rpm-package
  - local-test

rpm-package:
  stage: rpm-package
  script:
    - 'rpm-package.sh'

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'
  except:
    - master

e2e-localhost-preservation:
  stage: local-test
  script:
    - 'e2e-localhost.sh preservation'
  except:
    - master

e2e-localhost-access-rest-api:
  stage: local-test
  script:
    - 'e2e-localhost.sh access-rest-api'
  except:
    - master
