---
stages:
  - rpm-package
  - local-test
  - documentation

rpm-package:
  stage: rpm-package
  script:
    - 'rpm-package.sh'

unit-test:
  stage: local-test
  script:
    - 'unit-test.sh'

e2e-localhost-siptools-research:
  stage: local-test
  script:
    - 'e2e-fairdata-localhost.sh dpres-research-rest-api'
  except:
    - master

documentation:
  stage: documentation
  script:
    - 'documentation.sh'
  only:
    - develop
